### ISSUE TITLE
Model fine-tuned on Franka Emika Panda

### ISSUE THREAD

**Issue by ClousTom** [openvla/openvla#100]
Hi,

Im going to test OpenVLA on a Franka Emika Panda, before going on another robot. The model you tested for your paper, fine-tuned on a Franka Emika Panda, is it published?

It's for my thesis.

Cordially,
CT

**Comment by kpertsch** [comment]
Hey, we haven't released the models we finetuned in the paper, since they were finetuned on very narrow datasets (just <100 demos), so they would not work well for any robot but the one from which we collected demos.
The best way for you would be to collect demos in your target environment yourself and then use them to finetune the base OpenVLA model!
