### ISSUE TITLE
Question about fine-tune on my own robot

### ISSUE THREAD

**Issue by Yikai1** [openvla/openvla#105]
Hello, Thanks for open-sourcing the great work! 
Here are some problems I've encountered in fine-tuning with my ur robot dataset.

1. About VRAM when fine-tuning, It work well and use about 18G VRAM when I use a single 4090 RTX (24G) for training with the fine-tuning parameters: 
lr = 5e-4, batch_size = 1 (due to limited compute resources), grad_acc_steps = 4, lora_rank = 32
But out of memory will happen when I use multiple 4090 RTX for fine-tuning.The error log as follows:

`torch.cuda.OutOfMemoryError:`` CUDA out of memory. Tried to allocate 2.00 MiB. GPU 0 has a total capacity of 23.64 GiB of which 2.00 MiB is free. Process 264136 has 808.00 MiB memory in use. Process 264133 has 21.48 GiB memory in use. Process 264135 has 690.00 MiB memory in use. Process 264134 has 688.00 MiB memory in use. Of the allocated memory 282.47 MiB is allocated by PyTorch, and 21.53 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[2024-09-14 00:38:21,136] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 254906 closing signal SIGTERM
[2024-09-14 00:38:22,657] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 1 (pid: 254907) of binary: ``/home/ubuntu/anaconda3/envs/openvla/bin/python`

Only when I set grad_acc_steps = 1, this problem will not happen. (I don't know if setup such a small batch_size will affect the results. )
I guess it's about the Torch DDP, I looked up and tried to fix the problem, but I failed. I want to know exactly why this is and how to avoid it. 

2. About dataset when fine-tuning. I got lazy and only used one epoch for one task (naively hope It will be able to overfit), Unfortunately, the actual results are very poor, altought the accuracy is nearly 100% and loss nearly 0% in the training log. Please give me some advice on data collection, and how much epoch for one task is appropriate.

**Comment by kpertsch** [comment]
Hi thanks for reaching out!
Re memory usage: it's expected that gradient acc adds a memory overhead (because you need to keep the full gradients around at all times). DDP for multi-GPU training also is expected to add a small overhead in memory usage, so if your single-GPU grad acc setup is nearly maxing out the available GPU memory, it's possible that the DDP overhead pushes it over the limit. I don't have a 2x 4090 setup so I can't really test it unfortunately. 
If you have no way of using a GPU with more memory, and the single-GPU setup is too limiting, you could try experimenting with quantized finetuning (QLoRA) -- it's trivial to implement with the HuggingFace models, but I only briefly tried when we worked on the paper and training didn't seem to converge well with the settings I tried. I didn't investigate this further, but you could give this a try.

As for the performance of the finetuned model: if you observe high train acc it's probably not a problem of the model not fitting your data. As a first line of defense, I'd suggest to run a few training images through your *inference* pipeline (ie pretend that your test environment is producing them) and verify that you get comparable action accuracy to what you observe during training (maybe a bit lower since we predict action tokens autoregressively at inference time). Subtle errors in the inference pipeline are the most common source of issues (eg differences in normalization, image pre-processing, resizing etc).
For the demo data, I'd suggest to collect demonstrations with little multi-modality if you want to make your life easier, eg use a consistent strategy for solving any given task.
