### ISSUE TITLE
Question about augmentation during training and inference

### ISSUE THREAD

**Issue by DelinQu** [openvla/openvla#123]
Hi [kpertsch](https://github.com/kpertsch),
thanks so much for sharing the awesome project. I'm fine-tuning openvla in customized dataset.  I notice that the configurations in [finetune.py#L92](https://github.com/openvla/openvla/blob/46b752f477cc5773cc1234b2e82c0e2130e4e890/vla-scripts/finetune.py#L92) and [train.py#L72](https://github.com/openvla/openvla/blob/46b752f477cc5773cc1234b2e82c0e2130e4e890/vla-scripts/train.py#L72) are distinct. Why openvla close the `image_aug` parameter during training, but switch to open in fintuning? Could you share some precious insights? It'll be very helpful for me. Thanks Again!

**Comment by kpertsch** [comment]
Hi!
We use no image augmentation during pre-training since the dataset we train on (Open X-Embodiment) is already very diverse, so we figured image augmentation may not be needed and would just make convergence slower (we had compute limitations). During finetuning however, since the dataset is much smaller + less diverse, we did find image augmentation to be helpful for better policy performance, so we turn it on there.
