### ISSUE TITLE
Extract attention score from the vision backbone

### ISSUE THREAD

**Issue by wu-yutong-525** [openvla/openvla#143]
Hi there, 

  I try to create the attention score heatmap of the vision backbone model to see how it views the environment. However, I get this error:
```
Traceback (most recent call last):
  File "/home/yutong/SimplerEnv-OpenVLA/testing_attmap.py", line 36, in <module>
    outputs = vla.vision_backbone(**inputs,output_attentions=True)
  File "/home/yutong/miniconda3/envs/simpler_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yutong/miniconda3/envs/simpler_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: PrismaticVisionBackbone.forward() got an unexpected keyword argument 'output_attentions'
```
May I kindly ask if there is any approach to extracts the attention weights from the vision model?

**Comment by moojink** [comment]
Hi @wu-yutong-525,

`PrismaticVisionBackbone` is a custom class that doesn't by default have `output_attentions` as an available argument in the `forward()` function. See the definition of this class [here](https://github.com/openvla/openvla/blob/0214a0c7c09942fb8e0ec3c3948c00e4e8949911/prismatic/extern/hf/modeling_prismatic.py#L63C7-L63C30). If you want any custom functionality, you will to need add code for that in [`modeling_prismatic.py`](https://github.com/openvla/openvla/blob/main/prismatic/extern/hf/modeling_prismatic.py). For your specific purpose, you can inspect the intermediate representations of `self.featurizer` (SigLIP encoder; see [here](https://github.com/openvla/openvla/blob/0214a0c7c09942fb8e0ec3c3948c00e4e8949911/prismatic/extern/hf/modeling_prismatic.py#L78)) and/or `self.fused_featurizer` (DINOv2 encoder; see [here](https://github.com/openvla/openvla/blob/0214a0c7c09942fb8e0ec3c3948c00e4e8949911/prismatic/extern/hf/modeling_prismatic.py#L92)). Note that OpenVLA uses both of these because it has a fused SigLIP+DINOv2 vision encoder.

You can modify any of the OpenVLA function definitions in `modeling_prismatic.py`. If you do so, in order for the changes to take effect, you will need to copy the modified `modeling_prismatic.py` into the folder containing the OpenVLA checkpoint you are using to replace the default `modeling_prismatic` (which is cached somewhere on your machine when you download the model for the first time; you can specify the cache location by setting the `TRANSFORMERS_CACHE` environment variable).

-Moo Jin

**Comment by haofuly** [comment]
> Hi [@wu-yutong-525](https://github.com/wu-yutong-525),
> 
> `PrismaticVisionBackbone` is a custom class that doesn't by default have `output_attentions` as an available argument in the `forward()` function. See the definition of this class [here](https://github.com/openvla/openvla/blob/0214a0c7c09942fb8e0ec3c3948c00e4e8949911/prismatic/extern/hf/modeling_prismatic.py#L63C7-L63C30). If you want any custom functionality, you will to need add code for that in [`modeling_prismatic.py`](https://github.com/openvla/openvla/blob/main/prismatic/extern/hf/modeling_prismatic.py). For your specific purpose, you can inspect the intermediate representations of `self.featurizer` (SigLIP encoder; see [here](https://github.com/openvla/openvla/blob/0214a0c7c09942fb8e0ec3c3948c00e4e8949911/prismatic/extern/hf/modeling_prismatic.py#L78)) and/or `self.fused_featurizer` (DINOv2 encoder; see [here](https://github.com/openvla/openvla/blob/0214a0c7c09942fb8e0ec3c3948c00e4e8949911/prismatic/extern/hf/modeling_prismatic.py#L92)). Note that OpenVLA uses both of these because it has a fused SigLIP+DINOv2 vision encoder.
> 
> You can modify any of the OpenVLA function definitions in `modeling_prismatic.py`. If you do so, in order for the changes to take effect, you will need to copy the modified `modeling_prismatic.py` into the folder containing the OpenVLA checkpoint you are using to replace the default `modeling_prismatic` (which is cached somewhere on your machine when you download the model for the first time; you can specify the cache location by setting the `TRANSFORMERS_CACHE` environment variable).
> 
> -Moo Jin

Hi @moojink , thanks for detail explanation about `modeling_prismatic.py`. In my opinion, there are three same files `modeling_prismatic.py` in total, which are in `./prismatic/`, `checkpoint/`, and the cache location. When training, only the cache file is actually used. Why so many files? What is the usage of the file in `./prismatic/`? It is really confusing when debugging.
