### ISSUE TITLE
Error about SkipDecoding

### ISSUE THREAD

**Issue by JiayiCheung** [openvla/openvla#155]
![1731557249471](https://github.com/user-attachments/assets/f7c5515a-908f-4274-9233-3790cd39756d)
Hello, I would like to ask if you have encountered such a situation. I have commented out the EEF statement according to the method in another issue and used JOINT_POS, but I still encounter such a situation. I firmly believe that the definitions in the finetune and oxe files are matched with my file format (https://sites.google.com/view/berkeley-ur5/home#h.k4ude1kpgtzu) and according to my investigation statement, the index is empty. I would like to ask if you have encountered such a problem and ask how the author solved it. if you can report me, I will thank you very much。
![1731557649770](https://github.com/user-attachments/assets/ac8a6358-7e5a-4c88-bae1-acbe29e32b1b)
![1731557668453](https://github.com/user-attachments/assets/be12e32f-23fd-4057-85c7-de58fd1564ad)

**Comment by kpertsch** [comment]
I assume this is not a question about OpenVLA code, but code for converting data to RLDS?
If this is still an issue, it would be helpful to post a stacktrace so it's easier to spot where things are going wrong.
Will close this issue for now since it's been a while since you asked this question, but if it's still an issue, feel free to re-open!
