### ISSUE TITLE
Any plan to release a finetuned checkpoint? 

### ISSUE THREAD

**Issue by RunpeiDong** [openvla/openvla#16]
Dear authors,

Thank you for your excellent work. May I ask if you can release a fine-tuned checkpoint, such as the Droid-Wipe model or some of the Franka-Tabletop model? Besides, may I ask where I can download the fine-tuning datasets? 

Best,
Runpei

**Comment by kpertsch** [comment]
Hi!
We're not planning to release the finetuned checkpoints since they are finetuned on narrow datasets (<100 demos) with little scene variation, so it's very unlikely they would be able to work in any other scene than the one we collected the finetuning data for. Same holds for the finetuning dataset. 
The best way to use the model on your robot would be to collect a small finetuning dataset in your own scene and then use that for model adaptation with our `finetune.py` script.
