### ISSUE TITLE
Train_loss to become NaN

### ISSUE THREAD

**Issue by HanwenWangBUPT** [openvla/openvla#30]
Thank you very much for your outstanding work. I am conducting fine-tuning experiments using the cmu_stretch dataset. My data processing should be fine. I would like to ask if using float16 for computation could cause the train_loss to become NaN. Your code uses bfloat16, but my device, a Titan GPU, does not support this precision.

**Comment by siddk** [comment]
Yes - we use `bfloat16` instead of `float16` because [it captures a wider range of values ](https://cloud.google.com/tpu/docs/bfloat16) (basically can represent same range of values as `float32` albeit with less precision).

Unfortunately `float16` captures a smaller range of numbers, so when you train, you are more likely to run into overflow/underflow that leads to the NaN loss. We don't support float16 mixed precision training at this time.

**Comment by HanwenWangBUPT** [comment]
Thank you for your response. @siddk
