### ISSUE TITLE
An issue about full-fine tuning.

### ISSUE THREAD

**Issue by Zhangwenyao1** [openvla/openvla#44]
Thanks for your great work.
If want to use the openvla/openvla-7b as the initialized weights for full-fine tuning, what should I do.
How should I set the ”pretrained_checkpoint“， I try to set ”pretrained_checkpoint = openvla/openvla-7b", but it raise the error as following:
    raise ValueError(f"Couldn't find valid HF Hub Path `{hf_path = }`")
ValueError: Couldn't find valid HF Hub Path `hf_path = 'openvla/openvla-dev/pretrained/openvla/openvla-7b'`

**Comment by kpertsch** [comment]
Hi!
For the full fine-tuning script you need to use the OpenVLA weights in our "native" prismatic format, we recently uploaded them here: https://huggingface.co/openvla/openvla-7b-prismatic

A bit of explanation: we run the pre-training for all our models with the ["full training script"](https://github.com/openvla/openvla/blob/main/vla-scripts/train.py), and the format in which weights are stored here is as simple PyTorch checkpoints. When publishing these models to the HuggingFace hub, we need to run some conversion so that the checkpoints can be loaded via `transformers.AutoModel.from_pretrained()` (you can actually find the conversion script [here](https://github.com/openvla/openvla/blob/main/vla-scripts/extern/convert_openvla_weights_to_hf.py)). This converted checkpoint is what you find as `openvla/openvla-7b`. 

However, after conversion it is no longer compatible to our original training script (which does not use `transformers.AutoModel`). Thus, for using the full training script, you need to use the original checkpoints, before conversion, which we published on the hub as `openvla/openvla-7b-prismatic`. Just make sure that your final hf_path is set to this path.
