### ISSUE TITLE
About how to identify the instruction is done.

### ISSUE THREAD

**Issue by BankBro** [openvla/openvla#45]
I have acknowledged that the predicted action is in the form of delta. And it is necessary to predict a certain number of times to finish the instruction. So each time I get a new predicted action. But how do I know if the task is complete? When it is time for the openvla to stop, what would the model return, and how to identify the task has been done? Thanks!

**Comment by RZFan525** [comment]
I have the same question.

**Comment by Subuday** [comment]
At paper presentation he said that model has not been trained to produce done output.
So you can implement somewhat aka timer, or fine-tune the model on finished videos where the robot is finishing in stale position

**Comment by BankBro** [comment]
> At paper presentation he said that model has not been trained to produce done output. So you can implement somewhat aka timer, or fine-tune the model on finished videos where the robot is finishing in stale position

Thanks! I miss it!

**Comment by kpertsch** [comment]
Jup, @Subuday's answer is correct -- the current model is not trained to predict when it's done solving a task. 
Your options are:
1. implement a manual timeout (ie terminate the task after a fixed number of steps or via manual human intervention)
2. fine-tune the model on a dataset that shows the robot not moving after the task is done -- then the policy will naturally stop after completing a task
3. introduce an additional dimension to the action space during fine-tuning that corresponds to a "done" action and is only set to 1 at the end of the trajectory and 0 otherwise -- then you can use the value of this action at inference time to determine when the policy thinks that the task is done.

In our experiments we used a combination of 1 and 2.
