### ISSUE TITLE
yaw pitch roll or roll pitch yaw

### ISSUE THREAD

**Issue by maytusp** [openvla/openvla#6]
Hello,

I have a problem regarding the orientation order of the output action.

I see some datasets in Open-X-Embodiment (OXE) have an action vector defined as [yaw, pitch, roll] (for example TACO-Play https://www.tensorflow.org/datasets/catalog/taco_play), while other datasets have [roll, pitch, yaw]. 

I see the configuration in OXE is [roll, pitch yaw] so I guess the OpenVLA model trained on OXE is also [roll, pitch, yaw], am I correct?

**Comment by kpertsch** [comment]
Copying my answer from Twitter DMs here for visibility:

We don't control the action spaces for the individual datasets we train on, i.e. we **do not** align coordinate systems, control frequencies, etc. The extent of our alignment is "the first 3 action dims correspond to translation values, the next 3 to rotation values and the 7th to gripper open/close". Beyond that we don't control anything. This means that there may very well be datasets in our mix that use different euler angle definitions, as you pointed out. 

Note that this "don't align action spaces" practice follows prior X-embodiment work (RT-X, Octo) and is mainly a convenience since it's pretty tedious to go into every of the 30-or-so datasets in our training mix and figure out the exact action coordinate definition used. This would get even worse in the future as we scale to thousands of individual datasets in the mix. In practice, we suspect that there is not too much benefit from perfectly aligning the action definitions, since for example the camera viewpoints are all different anyways, but this intuition has not been thoroughly tested empirically.

If you want to use the model for a certain target configuration, you can just finetune it with a bit of data from your target domain and it will adopt the action space you need and learn to output such actions. If you want to use the model out of the box (ie without finetuning), you'd need to match one of the setups from the training datasets pretty closely (eg set up a Bridge-like WidowX with the BridgeDataV2 control stack) and then the model would output actions for the action space definition used in that dataset (implicitly, by recognizing the robot in the images).

**Comment by XiaoweiLinXL** [comment]
Hi, I have a question with the orientation representation. How do we deal with the singularity issue when using Euler angle? For example, if we use fixed frame RPY, when the gripper is facing down, i.e. Pitch = 90 deg, R and Y can have infinitely many solutions because it's in gimble lock. In this case, the state can fluctuate within these solutions. If we are using the difference of state to compute action, the action is not zero even though the gripper is actually not moving.
