### ISSUE TITLE
PrismaticVLM.generate() returns decoded_text, but OpenVLA uses generated_ids

### ISSUE THREAD

**Issue by KopanevPavel** [openvla/openvla#60]
Dear OpenVLA team! Thank you for open-sourcing the OpenVLA model! The project is amazing. 

I have a small question about model implementation. In generate() method for PrismaticVLM (https://github.com/openvla/openvla/blob/main/prismatic/models/vlms/prismatic.py#L621) you return decoded text but in predict_action() method of OpenVLA (https://github.com/openvla/openvla/blob/main/prismatic/models/vlas/openvla.py#L80) you use generated_ids (token ids, not decoded sequence). Maybe I missed something, can you please explain this part? Thank you

**Comment by kpertsch** [comment]
For OpenVLA, we want access to the generated token IDs, since we need to parse them back out into actions (we overwrite the least used tokens in the vocabulary to represent action tokens) -- so if we generated text outputs, we'd need to re-encode them into tokens anyways to compute the actions, so directly querying for tokens is more convenient.
