### ISSUE TITLE
Overwriting the least used tokens vs creating new ones

### ISSUE THREAD

**Issue by KopanevPavel** [openvla/openvla#71]
Dear OpenVLA authors! I have a question regarding the action tokenization process. As with RT-2, you use the 256 least used tokens for actions. Have you by any chance experimented with **adding new tokens** for actions (and then calling resize_token_embeddings() to resize embeddings)? Are there any obvious disadvantages to this approach?

**Comment by kpertsch** [comment]
We have not tried this, but it makes sense. It's just slightly less convenient since you need to carry around a new tokenizer vs just using the LLaMA tokenizer. I would expect this to work roughly equally well -- in my experience the exact choice of tokens you overwrite has very little influence on the training dynamics, but it would still be a cool thing to try!
