### ISSUE TITLE
Will openvla team release Finetuned Model?

### ISSUE THREAD

**Issue by zzj1111** [openvla/openvla#72]
Will openvla team release Finetuned Model? For example, Openvla model finetuned on Bridge data v2?

**Comment by kpertsch** [comment]
Thanks for reaching out!
The OpenVLA model already works well on BridgeDataV2 as is, no need to fine-tune it for that since it's already part of the pre-training mix.
We are not planning to release the fine-tuned models we used in the paper experiments since they are very specific to the scenes that we collected the fine-tuning data in, so it's unlikely they will work in any other scene / lab. Best is to collect data in your target environment and fine-tune a model yourself!
