### ISSUE TITLE
In SimplerENV, select google robot or WidowX, unnorm_key=bridge_orig, the effect is not good, can not complete the task.

### ISSUE THREAD

**Issue by zhou-pig** [openvla/openvla#84]
> Thank you!
Hello, my friend, I have the same problem as you. No matter what unnorm_key I choose, using OpenVLA doesn't work well in simpler env. Have you solved the problem?

_Originally posted by @zhou-pig in https://github.com/openvla/openvla/issues/21#issuecomment-2317058224_

**Comment by moojink** [comment]
Hi @zhou-pig,

I recently addressed this in the other issue (see my response [here](https://github.com/openvla/openvla/issues/7#issuecomment-2330572696)). To try OpenVLA in simulation, I would recommend using the LIBERO evaluation script that we recently pushed to the repo because it provides a way to train and test on the same distribution of data (rather than test on a real-to-sim distribution shift). Please see the [LIBERO Simulation Benchmark Evaluations](https://github.com/openvla/openvla?tab=readme-ov-file#libero-simulation-benchmark-evaluations) section in the README for instructions on how to run OpenVLA in LIBERO, and Appendix E in [v2 of the OpenVLA paper on arXiv](https://arxiv.org/abs/2406.09246) for more experimental details.

-Moo Jin
